### ISSUE TITLE
Order Management

### ISSUE THREAD

**Issue by wenjing-liu** [JavaScriptAcademy/oneStep#2]
- [ ] Shopping Cart Page
  -  [ ] list all chosen dishes #3 
    - [ ] list all orders of current user #30 
  -  [ ] checkout button #4 
  -  [ ] remove button for every chosen dishes #5 
  -  [ ] modify the quantity #6 
-  [ ] Delivery Info Page
  -  [ ] Select or input address, name, phone number, date time #7 
  -  [ ] Pay button #12 
-  [ ] Receipt Page 
  -  [ ] list order information which just ordered #10 
- [ ] Order Schema Defination #8 
- [ ] Order History
- [ ] receipt page #31
